[theme]
builtin = "Catppuccin"
mode = "auto"

[wallpaper.default]
path = "~/Images/Wallpaper/Altered/Seeds-of-Unity.jpg"

[location]
auto_locate = true

[nightlight]
enabled = true

[plugins]
enabled = ["yuuto/arch-updater"]

[plugin_settings."yuuto/arch-updater"]
auto_check_hours = 1
panel_placement = "floating"

[shell.panel]
control_center_placement = "floating"
session_placement = "floating"
