[include]
files = ["bars/waybar.toml"]

[theme]
builtin = "Catppuccin"
mode = "auto"

[location]
auto_locate = true

[nightlight]
enabled = true

[bar.default]
enabled = false

[plugins]
enabled = ["yuuto/arch-updater"]

[plugin_settings."yuuto/arch-updater"]
auto_check_hours = 1
panel_placement = "floating"

[shell.panel]
control_center_placement = "floating"
session_placement = "floating"
