[idle.behavior.lock]
timeout = 90
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 180
action = "screen_off"
enabled = true

[idle.behavior.suspend]
timeout = 300
action = "suspend"

[lockscreen]
blur_intensity = 0
tint_intensity = 0
wallpaper = "~/Images/Wallpaper/SFW/owl_drawing.png"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = ["lockscreen-login-box@HDMI-A-2", "lockscreen-login-box@eDP-1", "clock", "date", "weather", "media"]

[lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
box_height = 70.0
box_width = 368.0
cx = 960.0
cy = 540.0
output = "HDMI-A-2"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
background_color = "surface_variant"
background_opacity = 0.0
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 70.0
box_width = 368.0
cx = 960.0
cy = 540.0
output = "eDP-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.0
background_radius = 12.0
center_password_text = true
input_opacity = 1.0
input_radius = 28.0
layout = "compact"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = false
show_media = true
show_session_buttons = false
show_unlock_hint = false
show_weather = false

[lockscreen_widgets.widget.clock]
box_height = 176.0
box_width = 288.0
cx = 288.0
cy = 88.0
placement_height = 1080.0
placement_width = 1920.0
rotation = -0.0
type = "clock"

[lockscreen_widgets.widget.clock.settings]
background = false
clock_style = "digital"
format = "{:%H:%M}"

[lockscreen_widgets.widget.date]
box_height = 112.0
box_width = 384.0
cx = 352.0
cy = 180.0
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.date.settings]
background = false
format = "{:L%A %d %B}"

[lockscreen_widgets.widget.weather]
box_height = 160.0
box_width = 272.0
cx = 976.0
cy = 988.0
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "weather"

[lockscreen_widgets.widget.weather.settings]
background = false
shadow = true
show_forecast = true

[lockscreen_widgets.widget.media]
type = "media_player"
cx = 960.0
cy = 635.0
placement_height = 1080.0
placement_width = 1920.0

[lockscreen_widgets.widget.media.settings]
hide_when_no_media = true
background = false
color = "on_surface"
