[idle.behavior.lock]
timeout = 90
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 180
action = "screen_off"
enabled = true

[idle.behavior.suspend]
timeout = 300
action = "suspend"

[lockscreen]
blur_intensity = 0
tint_intensity = 0
wallpaper = "~/Images/Wallpaper/SFW/owl_drawing.png"

[lockscreen_widgets]
enabled = true
schema_version = 2

[lockscreen_widgets.widget.clock]
box_height = 176.0
box_width = 288.0
cx = 288.0
cy = 88.0
placement_height = 1080.0
placement_width = 1920.0
rotation = -0.0
type = "clock"

[lockscreen_widgets.widget.clock.settings]
background = false
clock_style = "digital"
format = "{:%H:%M}"

[lockscreen_widgets.widget.date]
box_height = 112.0
box_width = 384.0
cx = 352.0
cy = 180.0
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.date.settings]
background = false
format = "{:L%A %d %B}"

[lockscreen_widgets.widget.weather]
box_height = 160.0
box_width = 272.0
cx = 976.0
cy = 988.0
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "weather"

[lockscreen_widgets.widget.weather.settings]
show_forecast = true
background = false

[lockscreen_widgets.widget.media]
type = "media_player"
cx = 960.0
cy = 635.0
placement_height = 1080.0
placement_width = 1920.0

[lockscreen_widgets.widget.media.settings]
hide_when_no_media = true
background = false
color = "on_surface"
