#!/bin/zsh
# ------------------------------------------------------------
# ---                     shell aliases                    ---
# ------------------------------------------------------------


# -- Colours command
# ---------------------------
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# -- git aliases
# ---------------------------
alias gp='git pull'
alias gP='git push'

# -- ls aliases
# ---------------------------
alias la='ls -A'
alias ll='ls -Al'

# -- docker aliases
# ---------------------------
alias d='docker'
alias dc='docker container ls'
alias di='docker image ls'

# -- Alt names
# ---------------------------
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias lg='lazygit'
alias cm='chezmoi'
alias py='python'


# -- Command config
# ---------------------------
alias feh='feh --scale-down --auto-zoom'


# -- New commands
# ---------------------------
alias apv='mpv --volume=50 --no-audio-display'
alias venv="source .venv/bin/activate"
alias compress='tar zcvf archive.tar.gz'
alias decompress='tar zxvf'
alias docker_clean="docker system prune"
dunst_test() {
    dunstify "Urgence : normale" "Une annonce importante mais sans plus"
    dunstify -u low "Urgence : faible" "C'est bien pour genre ... spotify, vraiment juste une info sans risque"
    dunstify -u critical "Urgence : critique" "Comme on dit chez moi, on est pas dans la merde !"
}


# -- Fast config access
# ---------------------------
alias cedit='chezmoi edit --watch'
alias aliases='cedit $ZDOTDIR/aliases'
alias zshenv='cedit $ZDOTDIR/.zshenv'
alias zshrc='cedit $ZDOTDIR/.zshrc'
alias dotfiles='cd $HOME/.local/share/chezmoi ; nvim ; cm apply'

# -- Kittens
# ---------------------------
alias kitten='kitty +kitten'
alias icat='kitten icat'
alias connect='kitten ssh'


# -- Host specific configs
# ---------------------------


case $DISTRO in

    "Ubuntu") 
        # -- System functions
        # ---------------------------
        alias update='sudo apt update ; sudo apt upgrade ; sudo apt autoremove ; sudo snap refresh ; uv self update ; chezmoi update -v'
        ;;
    "Arch Linux")
        # -- System functions
        # ---------------------------
        alias update='paru -Pw ; paru -Sc ; paru -Syu ; pacdiff -s ; chezmoi update -v'
        # -- Replace commands
        # ---------------------------
        alias ls='lsd'
        ;;
esac



case $HOSTNAME in

  "gonto")
    # -- System functions
    # ---------------------------
    alias backup="cp -nrv /home/nmaignan/Documents/Zotero/storage /media/nmaignan/HDD Arcé ; cp -nrv /home/nmaignan/Thèse /media/nmaignan/HDD Arcé"
    alias cp_zotero="cp -nr Documents/Zotero/storage/ /media/nmaignan/Clyde/Transfert\ Rapide/"
    # -- Misc
    # ---------------------------
    alias cat="batcat"
    alias clean_cache="sh /home/nmaignan/Applications/clean.sh"
    alias journal="nvim $HOME/Thèse/01_Documents/Journal\ de\ bord\ -\ Thèse.md"
    ;;

  "nascane")
    # -- System functions
    # ---------------------------
    alias backup='sh ~/Applications/Scripts/backup.sh'
    alias background-cli='sh ~/Applications/Scripts/choice.sh'
        # -- New commands
    # ---------------------------
    alias matlab='~/Applications/Matlab/R2023a/bin/matlab -nodesktop'
    alias matlab-gui='~/Applications/Matlab/R2023a/bin/matlab'
    alias ssh_gonto="ssh nmaignan@gonto -L 8008:localhost:8008 -X -t 'zsh -l'"
    ;;

  "wrandrall")
    alias ssh_gonto="ssh nmaignan@gonto -L 8008:localhost:8008 -X -t 'zsh -l'"
    ;;


esac

