#!/bin/zsh
# ------------------------------------------------------------
# ---                    zsh environment                   ---
# ------------------------------------------------------------

# Please create a symlink of this file to your $HOME


# -- Variables
# ---------------------------
export DIFFPROG="nvim -d"
export DISTRO="$(if [ -f /etc/os-release ]; then . /etc/os-release; echo "$NAME"; fi)"
export EDITOR="$(command -v nvim)"
export HOSTNAME=$(hostname)
export LANG="fr_FR.UTF-8"
export PYTHONPYCACHEPREFIX="${HOME}/.cache/Python"
export SHELL="$(command -v zsh)"
export VISUAL=$EDITOR
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export ZDOTDIR=${HOME}/.config/zsh

# -- ssh-agent
# ---------------------------
if [[ -z "$SSH_AUTH_SOCK" ]] ; then
    eval `ssh-agent -s`
    ssh-add
fi

# -- Neovim under Ubuntu
# ---------------------------
if [[ $DISTRO = "Ubuntu" ]]; then
    export PATH=/snap/node/current/bin:$PATH
fi

# -- Hyprland
# ---------------------------
if [[ $HOSTNAME = "nascane" && -z "${WAYLAND_DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
    export GOPATH=$HOME/.go
    export _JAVA_AWT_WM_NONREPARENTING=1
    exec Hyprland
fi

