#!/bin/zsh
# ---------------------------------------------------------
# ---                 zsh run commands                  ---
# ---------------------------------------------------------


# -- Variables
# ---------------------------
ZSH_DOTFILES=${HOME}/.config/zsh


# -- History
# ---------------------------
HISTFILE=${ZSH_DOTFILES}/.histfile
HISTSIZE=1000
SAVEHIST=5000


# -- Completion
# ---------------------------
fpath+=${ZSH_DOTFILES}/completions
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
# matcher-list 'm:{a-zA-Z}={A-Za-z}'


# -- Aliases
# ---------------------------
source ${ZSH_DOTFILES}/aliases


# -- Prompt
# ---------------------------
setopt prompt_subst
autoload -Uz vcs_info
precmd () { vcs_info }
zstyle ':vcs_info:git:*' formats '%b'
get_vcs_info_prompt() {
    if [[ -n $vcs_info_msg_0_ ]]; then
        echo " %F{green}%B%F{black}%K{green}%B ${vcs_info_msg_0_}%b%F{green}%k"
    else
        echo ""
    fi
}
PROMPT='%F{magenta}%B%F{black}%K{magenta}%B%n@%m%b%F{magenta}%k$(get_vcs_info_prompt)%f%k%B %D{%A %d %B} %D{%H:%M}
%}%F{magenta}%k%B%~/%b%k%f '


# -- Miscellaneous
# ---------------------------
bindkey -v
source ${HOME}/.config/ranger/shell_automatic_cd.sh


# -- Host specific conf
# ---------------------------
case $HOSTNAME in

    "gonto")
        # -- Suggestions and colours
        # ---------------------------
        source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
        # -- Conda
        # ---------------------------
        __conda_setup="$('/home/nmaignan/Applications/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
        if [ $? -eq 0 ]; then
            eval "$__conda_setup"
        else
            if [ -f "/home/nmaignan/Applications/miniconda3/etc/profile.d/conda.sh" ]; then
                . "/home/nmaignan/Applications/miniconda3/etc/profile.d/conda.sh"
            else
                export PATH="/home/nmaignan/Applications/miniconda3/bin:$PATH"
            fi
        fi
        unset __conda_setup
        # -- Miscellaneous
        # ---------------------------
        fpath+=${HOME}/Applications/conda-zsh-completion
        zstyle ':completion::complete:*' use-cache 1
        zstyle ":conda_zsh_completion:*" sort-envs-by-time true
        zstyle ":conda_zsh_completion:*" show-global-envs-first true
        ;;

    "nascane")
        # -- Suggestions and colours
        # ---------------------------
        source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
        # -- Conda
        # ---------------------------
        __conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
        if [ $? -eq 0 ]; then
            eval "$__conda_setup"
        else
            if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
                . "/opt/miniconda3/etc/profile.d/conda.sh"
            else
                export PATH="/opt/miniconda3/bin:$PATH"
            fi
        fi
        unset __conda_setup
        ;;

    *)
        echo "ptdr t ki"
        ;;

esac
