#!/bin/zsh
# ------------------------------------------------------------
# ---                    zsh environment                   ---
# ------------------------------------------------------------

# Please create a symlink of this file to your $HOME

# -- Variables
# ---------------------------
export VISUAL="$(command -v nvim)"
export EDITOR=$VISUAL
export SHELL="$(command -v zsh)"
export HOSTNAME=$(hostname)
export PYTHONPYCACHEPREFIX="${HOME}/.cache/Python"
export ZDOTDIR=${HOME}/.config/shell/zsh
export LANG="fr_FR.UTF-8"

# -- ssh-agent
# ---------------------------
#export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

# -- sway
# ---------------------------
if [ $HOSTNAME = "nascane" ] && [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec sway
fi

