#!/bin/zsh
# ------------------------------------------------------------
# ---                    zsh environment                   ---
# ------------------------------------------------------------

# Please create a symlink of this file to your $HOME

# -- Variables
# ---------------------------
export VISUAL="$(command -v nvim)"
export EDITOR=$VISUAL
export SHELL="$(command -v zsh)"
export HOSTNAME=$(hostname)
export PYTHONPYCACHEPREFIX="${HOME}/.cache/Python"
export ZDOTDIR=${HOME}/.config/shell/zsh
