#!/bin/zsh

# Couleurs dans le terminal
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Alias pour ls
alias la='ls -A'
alias ll='ls -Al'

# Alias pour supplanter d'autres commandes
alias vim='nvim'
alias vi='nvim'
alias lg='lazygit'
alias apv='mpv --volume=50 --no-audio-display'
alias feh='feh --scale-down --auto-zoom'

# Archivage
alias compress='tar zcvf archive.tar.gz'
alias decompress='tar zxvf'


# Divers
alias venv="source .venv/bin/activate"
alias docker_clean="docker system prune"

# Modifications config
alias aliases='chezmoi edit $HOME/.config/shell/aliases ; chezmoi apply'
alias zshenv='chezmoi edit $HOME/.config/shell/zsh/.zshenv ; chezmoi apply'
alias zshrc='chezmoi edit $HOME/.config/shell/zsh/.zshrc ; chezmoi apply'


case $HOSTNAME in

  "gonto")
    # Mises à jour
    alias update='sudo apt update ; sudo apt upgrade ; sudo apt autoremove ; python /home/nmaignan/Applications/update_pip.py'
    # Backups
    alias backup="cp -nrv /home/nmaignan/Documents/Zotero/storage /media/nmaignan/HDD Arcé ; cp -nrv /home/nmaignan/Thèse /media/nmaignan/HDD Arcé"
    alias cp_zotero="cp -nr Documents/Zotero/storage/ /media/nmaignan/Clyde/Transfert\ Rapide/"
    # Divers
    alias clean_cache="sh /home/nmaignan/Applications/clean.sh"
    alias journal="nvim $HOME/Bureau/Journal\ de\ bord\ -\ Thèse.txt"
    ;;

  "nascane")
    # Système
    alias update='yay -Pw && yay -Sc && yay -Syu --sudoloop && yay -Yc && sudo pacdiff'
    alias day_mode='pkill -USR1 redshift'
    alias retirer='sh ~/Applications/Scripts/umount.sh'
    alias backup='sh ~/Applications/Scripts/backup.sh'
    # Fonds d'écran
    alias background-cli='sh ~/Applications/Scripts/choice.sh'
    # Applications
    alias convertir='sh ~/Applications/Scripts/convertisseur.sh'
    alias video2gif='sh ~/Applications/Scripts/video2gif.sh'
    alias matlab='~/Applications/Matlab/R2023a/bin/matlab -nodesktop'
    alias matlab-gui='~/Applications/Matlab/R2023a/bin/matlab'
    # Private aliases
    source $HOME/.config/shell/aliases_nascane
    ;;


esac
