#!/bin/zsh
# ------------------------------------------------------------
# ---                     shell aliases                    ---
# ------------------------------------------------------------


# -- Colours command
# ---------------------------
alias grep='grep --color=auto'


# -- Replace commands
# ---------------------------
alias ls='lsd'
alias cat='bat'


# -- ls aliases
# ---------------------------
alias la='ls -A'
alias ll='ls -Al'


# -- Alt names
# ---------------------------
alias vi='nvim'
alias vim='nvim'
alias lg='lazygit'
alias cm='chezmoi'


# -- Command config
# ---------------------------
alias feh='feh --scale-down --auto-zoom'


# -- New commands
# ---------------------------
alias apv='mpv --volume=50 --no-audio-display'
alias venv="source .venv/bin/activate"
alias compress='tar zcvf archive.tar.gz'
alias decompress='tar zxvf'
alias docker_clean="docker system prune"


# -- Fast config access
# ---------------------------
alias cedit='chezmoi edit --watch'
alias aliases='cedit $HOME/.config/shell/aliases'
alias zshenv='cedit $HOME/.config/shell/zsh/.zshenv'
alias zshrc='cedit $HOME/.config/shell/zsh/.zshrc'


# -- Kittens
# ---------------------------
alias kitten='kitty +kitten'
alias icat='kitten icat'


# -- Host specific configs
# ---------------------------
case $HOSTNAME in

  "gonto")
    # -- System functions
    # ---------------------------
    alias update='sudo apt update ; sudo apt upgrade ; sudo apt autoremove ; sudo snap refresh ; chezmoi update -v'
    alias backup="cp -nrv /home/nmaignan/Documents/Zotero/storage /media/nmaignan/HDD Arcé ; cp -nrv /home/nmaignan/Thèse /media/nmaignan/HDD Arcé"
    alias cp_zotero="cp -nr Documents/Zotero/storage/ /media/nmaignan/Clyde/Transfert\ Rapide/"
    # -- Misc
    # ---------------------------
    alias cat="batcat"
    alias clean_cache="sh /home/nmaignan/Applications/clean.sh"
    alias journal="nvim $HOME/Thèse/01_Documents/Journal\ de\ bord\ -\ Thèse.txt"
    ;;

  "nascane")
    # -- System functions
    # ---------------------------
    alias update='yay -Pw && yay -Sc && yay -Syu --sudoloop && yay -Yc && pacdiff ; chezmoi update -v'
    alias day_mode='pkill -USR1 redshift'
    alias retirer='sh ~/Applications/Scripts/umount.sh'
    alias backup='sh ~/Applications/Scripts/backup.sh'
    alias background-cli='sh ~/Applications/Scripts/choice.sh'
    # -- New commands
    # ---------------------------
    alias convertir='sh ~/Applications/Scripts/convertisseur.sh'
    alias video2gif='sh ~/Applications/Scripts/video2gif.sh'
    alias matlab='~/Applications/Matlab/R2023a/bin/matlab -nodesktop'
    alias matlab-gui='~/Applications/Matlab/R2023a/bin/matlab'
    alias ssh_gonto="kitten ssh nmaignan@gonto -L 8008:localhost:8008 -X -t 'zsh -l'"
    # -- Private aliases
    # ---------------------------
    source $HOME/.config/shell/aliases_nascane
    ;;

esac

