-- NOTE: Highlight, edit, and navigate code
return {
    {
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        build = ":TSUpdate",
        main = "nvim-treesitter.configs",
        opts = {
            ensure_installed = {
                "bash",
                "bibtex",
                "css",
                "dockerfile",
                "gitignore",
                "html",
                "hyprlang",
                "java",
                "javadoc",
                "json",
                -- "kitty",
                -- "latex",
                "lua",
                "luadoc",
                "markdown",
                "markdown_inline",
                "matlab",
                "python",
                "regex",
                "requirements",
                "ssh_config",
                "toml",
                "vim",
                "vimdoc",
                "yaml",
                "zathurarc",
                -- "zsh",
            },
        },
    },
}
