#! /bin/sh

# Get my dotfiles
if ! command -v chezmoi >/dev/null 2>&1; then
    snap install chezmoi --classic
    chezmoi init --apply https://gitlab.com/nifra/dotfiles.git
fi

# Packages install
sudo apt install -y btop dunst kitty neofetch ranger xclip zathura zsh zsh-syntax-highlighting zsh-autosuggestions
sudo snap install discord
sudo snap install brave
sudo snap install mpv
sudo snap install zotero-snap
sudo snap install node --classic
sudo snap install nvim --classic

# Brave
if ! command -v brave-browser >/dev/null 2>&1; then
    sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    sudo apt update
    sudo apt install brave-browser
fi

# Lazygit
if ! command -v lazygit >/dev/null 2>&1; then
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit /usr/local/bin
    rm lazygit lazygit.tar.gz
fi

# uv
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

# Nerd Fonts
if [ "$(fc-list | grep -ci 'JetBrainsMono Nerd Font')" -eq 0 ]; then
    zsh ~/.scripts/nerd_fonts_install.bash
fi

# Install regolith
if ! command -v regolith-diagnostic >/dev/null 2>&1; then
    wget -qO - https://regolith-desktop.org/regolith.key |
        gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg >/dev/null
    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
https://regolith-desktop.org/release-3_1-ubuntu-jammy-amd64 jammy main" |
        sudo tee /etc/apt/sources.list.d/regolith.list
    sudo apt update
    sudo apt install regolith-desktop regolith-session-flashback regolith-look-lascaille i3xrocks-bluetooth i3xrocks-disk-capacity i3xrocks-media-player i3xrocks-weather
    echo "Plus qu'à reboot !"
fi
